### PR TITLE
Refactor to use autoloading for functions

### PR DESCRIPTION
**Pull request by dchenbecker**
Also made more use of explicit pathnames rather than trying to deduce
from $0 (not always compatible with autoloading).

Syntax highlighting gets lost, although I think I could add a shebang to each function file and that would help GitHub figure things out.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Ah, this is something I've wanted to do for a while. Did you notice any speedup in the loading time?

**Comment by Tarrasch** [comment]
Thank you very much. Have you found this plugin valuable in overall? :)

**Comment by dchenbecker** [comment]
Speed up time is a bit faster, but it was already relatively fast. I'm just starting to play around with the plugin, so I'll have to digest a bit before providing feedback. Thanks!

**Comment by Tarrasch** [comment]
Cool! :)

**Comment by Tarrasch** [comment]
@dchenbecker, out of curiosity, did you ever start to use this plugin? :)

**Comment by dchenbecker** [comment]
I did a little and then started using eshell/elisp. I still use zsh a ton but the work I do now doesn't really need as much from the shell level :)

**Pull request merged**
